### ISSUE TITLE
unable to build binary

### ISSUE THREAD

**Issue by Astrali** [bva/vault-pps-plugin#1]
Hi,
i tried the "simple" command to compile the project and failed.
i also cloned the repository and tried to modify the dependencies to older versions from the hashicorp vault repo as they removed some of the dependent folders.
But whatever i try i get a fallback to "@latest" and i am unable to build the binary - could you update your project or build instructions?

Thank you very much!
Appreciate your help

**Comment by bva** [comment]
I have updated code to match latest Vault SDK, and also made project to use go modules for dependencies.
Please, try v1.0.0

**Comment by Astrali** [comment]
Thank you very much!
After upgrading from Ubuntu's default "go 1.13" to "go 1.17" the process worked flawless and i got the executable now.
i'll need some time to test the rest but i see this issue as solved now.
